AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create Security Group, Key Pair, and EC2 instance.
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0    
  MyInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f34c5ae932e6f0e4
      SecurityGroupIds:
        - !GetAtt "MySecurityGroup.GroupId"
      UserData: !Base64 |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          yum install -y git
          git clone https://github.com/notonprem/website_template.git
          sudo cp -r website_template/* /var/www/html/
Outputs:
  PublicIp:
    Description: MyInstance PublicIp
    Value: !GetAtt MyInstance.PublicIp                 
